In [1]:
import pandas as pd

nyc_open = pd.read_csv('~/Desktop/workspace/FinalProject/RGTM-master/Cleaned/merged_manhattan_cleanup.csv', header = 0)
zillow = pd.read_csv('~/Desktop/workspace/FinalProject/merged_zillow_cleanup.csv', header = 0)

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (15,16,20) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
# Fill in missing values for AptNum
nyc_open['AptNum'] = nyc_open['AptNum'].fillna('House')
zillow['AptNum'] = zillow['AptNum'].fillna('House')

# Remove all the spaces
nyc_open['AptNum'] = nyc_open['AptNum'].str.strip()
zillow['AptNum'] = zillow['AptNum'].str.strip()
nyc_open['StreetNum'] = nyc_open['StreetNum'].str.strip()
zillow['StreetNum'] = zillow['StreetNum'].str.strip()
nyc_open['StreetName'] = nyc_open['StreetName'].str.strip()
zillow['StreetName'] = zillow['StreetName'].str.strip()

# Drop rows with no AptNum
indexNames = nyc_open[nyc_open['AptNum'].isna()].index
nyc_open = nyc_open.drop(indexNames)
print(nyc_open.shape)
indexNames = zillow[zillow['AptNum'].isna()].index
zillow = zillow.drop(indexNames)
print(zillow.shape)

(67349, 22)
(20408, 6)

In [3]:
# Match apartments 
matched = pd.merge(nyc_open, zillow, on = ['StreetNum', 'StreetName', 'AptNum', 'ZipCode'])
matched

,Year,Neighborhood,BuildingCategoryNum,BuildingCategoryDes,TaxClassAtPresent,Block,Lot,BuildingClassAtPresent,StreetNum,StreetName,...,TotalUnits,LandSquareFeet,GrossSquareFeet,YearBuilt,TaxClassAtTimeOfSale,BuildingClassAtTimeOfSale,SalePrice,SaleDate,Beds,Baths
0,2015,ALPHABET CITY,1,ONE FAMILY DWELLINGS,1,400,19,A4,526,EAST 5TH STREET,...,1,1883,5200,1900,1,A4,6500000,3/18/2015,7,5
1,2018,ALPHABET CITY,1,ONE FAMILY DWELLINGS,1,400,19,A4,526,EAST 5TH STREET,...,1,1883,5200,1900,1,A4,6100000,12/3/2018,7,5
2,2019,ALPHABET CITY,1,ONE FAMILY DWELLINGS,1,400,19,A4,526,EAST 5TH STREET,...,1,"1,883","5,200",1900,1,A4,"6,100,000",12/03/2018,7,5
3,2015,ALPHABET CITY,3,THREE FAMILY DWELLINGS,1,376,24,C0,264,EAST 7TH STREET,...,3,2059,3696,1900,1,C0,3775000,10/22/2015,8,5
4,2016,ALPHABET CITY,3,THREE FAMILY DWELLINGS,1,376,24,C0,264,EAST 7TH STREET,...,3,2059,3696,1900,1,C0,7738700,12/22/2016,8,5
5,2015,ALPHABET CITY,9,COOPS - WALKUP APARTMENTS,2,376,19,C6,254,EAST 7TH STREET,...,0,0,0,1910,2,C6,600000,8/20/2015,0,1
6,2015,ALPHABET CITY,9,COOPS - WALKUP APARTMENTS,2,389,30,C6,224,EAST 7TH STREET,...,0,0,0,1950,2,C6,355000,5/21/2015,0,1
7,2018,ALPHABET CITY,9,COOPS - WALKUP APARTMENTS,2,389,30,C6,224,EAST 7TH STREET,...,0,0,0,1950,2,C6,409000,10/9/2018,0,1
8,2019,ALPHABET CITY,9,COOPS - WALKUP APARTMENTS,2,389,30,C6,224,EAST 7TH STREET,...,0,0,0,1950,2,C6,"409,000",10/09/2018,0,1
9,2015,ALPHABET CITY,9,COOPS - WALKUP APARTMENTS,2,394,52,C6,633,EAST 11TH STREET,...,0,0,0,1937,2,C6,482500,9/9/2015,1,1
10,2015,ALPHABET CITY,9,COOPS - WALKUP APARTMENTS,2,394,52,C6,633,EAST 11TH STREET,...,0,0,0,1937,2,C6,495000,11/12/2015,1,1
11,2015,ALPHABET CITY,10,COOPS - ELEVATOR APARTMENTS,2,398,8,D4,160,EAST 3RD STREET,...,0,0,0,1940,2,D4,750430,6/15/2015,2,1
12,2019,ALPHABET CITY,10,COOPS - ELEVATOR APARTMENTS,2,398,8,D4,160,EAST 3RD STREET,...,0,0,0,1940,2,D4,"1,050,000",09/20/2019,2,1
13,2015,CHELSEA,1,ONE FAMILY DWELLINGS,1,771,52,A9,224,WEST 22ND STREET,...,1,1975,3855,1901,1,A9,8800000,12/11/2015,6,6
14,2016,CHELSEA,1,ONE FAMILY DWELLINGS,1,771,52,A9,224,WEST 22ND STREET,...,1,1975,3540,1901,1,A9,7425000,12/30/2016,6,6
15,2015,CHELSEA,9,COOPS - WALKUP APARTMENTS,2,742,60,C6,340,WEST 19TH STREET,...,0,0,0,1920,2,C6,795000,4/13/2015,2,1
16,2018,CHELSEA,9,COOPS - WALKUP APARTMENTS,2,742,60,C6,340,WEST 19TH STREET,...,0,0,0,1920,2,C6,999000,6/14/2018,2,1
17,2015,CHELSEA,9,COOPS - WALKUP APARTMENTS,2,742,60,C6,340,WEST 19TH STREET,...,0,0,0,1920,2,C6,949000,5/27/2015,2,1
18,2019,CHELSEA,9,COOPS - WALKUP APARTMENTS,2,742,60,C6,340,WEST 19TH STREET,...,0,0,0,1920,2,C6,"930,000",07/24/2019,2,1
19,2015,CHELSEA,9,COOPS - WALKUP APARTMENTS,2,744,32,C6,309,WEST 20TH STREET,...,0,0,0,1850,2,C6,570000,6/25/2015,1,1
20,2019,CHELSEA,9,COOPS - WALKUP APARTMENTS,2,744,32,C6,309,WEST 20TH STREET,...,0,0,0,1850,2,C6,"585,000",05/02/2019,1,1
21,2015,CHELSEA,9,COOPS - WALKUP APARTMENTS,2,746,72,C6,356,WEST 23RD STREET,...,0,0,0,1910,2,C6,750000,10/22/2015,1,1
22,2018,CHELSEA,9,COOPS - WALKUP APARTMENTS,2,746,72,C6,356,WEST 23RD STREET,...,0,0,0,1910,2,C6,855000,6/15/2018,1,1
23,2015,CHELSEA,9,COOPS - WALKUP APARTMENTS,2,765,59,C6,228,WEST 16TH STREET,...,0,0,0,1901,2,C6,459000,10/19/2015,1,1
24,2018,CHELSEA,9,COOPS - WALKUP APARTMENTS,2,765,59,C6,228,WEST 16TH STREET,...,0,0,0,1901,2,C6,550000,7/16/2018,1,1
25,2015,CHELSEA,10,COOPS - ELEVATOR APARTMENTS,2,694,42,D4,520,WEST 23RD STREET,...,0,0,0,2003,2,D4,660000,6/8/2015,0,1
26,2015,CHELSEA,10,COOPS - ELEVATOR APARTMENTS,2,694,42,D4,520,WEST 23RD STREET,...,0,0,0,2003,2,D4,835000,10/5/2015,1,1
27,2015,CHELSEA,10,COOPS - ELEVATOR APARTMENTS,2,694,42,D4,520,WEST 23RD STREET,...,0,0,0,2003,2,D4,850000,1/13/2015,1,1
28,2017,CHELSEA,10,COOPS - ELEVATOR APARTMENTS,2,694,42,D4,520,WEST 23RD STREET,...,0,0,0,2003,2,D4,850000,6/22/2017,1,1
29,2015,CHELSEA,10,COOPS - ELEVATOR APARTMENTS,2,744,1,D4,365,WEST 20TH STREET,...,0,0,0,1928,2,D4,855000,9/18/2015,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10423,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2179,1,D4,875,WEST 181ST STREET,...,0,0,0,1917,2,D4,"1,273,500",07/24/2019,2,2
10424,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,633,D4,295,BENNETT AVENUE,...,0,0,0,1951,2,D4,"255,000",05/15/2019,0,1
10425,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,192,D4,120,BENNETT AVENUE,...,0,0,0,1939,2,D4,"275,000",01/08/2019,0,1
10426,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,633,D4,295,BENNETT AVENUE,...,0,0,0,1951,2,D4,"355,000",05/20/2019,1,1
10427,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,70,D4,24-42,BENNETT AVENUE,...,0,0,0,1920,2,D4,"377,500",05/22/2019,1,1
10428,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,192,D4,120,BENNETT AVENUE,...,0,0,0,1939,2,D4,"410,000",09/18/2019,1,1
10429,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,633,D4,295,BENNETT AVENUE,...,0,0,0,1951,2,D4,"415,000",08/26/2019,1,1
10430,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,633,D4,4501,BROADWAY,...,0,0,0,1951,2,D4,"418,000",08/28/2019,1,1
10431,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,326,D4,153,BENNETT AVENUE,...,0,0,0,1951,2,D4,"420,000",03/29/2019,1,1
10432,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,326,D4,143,BENNETT AVENUE,...,0,0,0,1951,2,D4,"422,000",06/20/2019,1,1
10433,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,70,D4,24-42,BENNETT AVENUE,...,0,0,0,1920,2,D4,"436,527",08/29/2019,1,1
10434,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,169,D4,100,BENNETT AVENUE,...,0,0,0,1939,2,D4,"450,000",06/13/2019,1,1
10435,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,166,D4,736,WEST 186TH STREET,...,0,0,0,1939,2,D4,"460,000",08/29/2019,1,1
10436,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,614,D4,720,FORT WASHINGTON AVENUE,...,0,0,0,1939,2,D4,"525,000",02/13/2019,1,1
10437,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,166,D4,736,WEST 186TH STREET,...,0,0,0,1939,2,D4,"547,500",08/27/2019,2,1
10438,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,633,D4,263,BENNETT AVENUE,...,0,0,0,1951,2,D4,"567,500",05/07/2019,2,1
10439,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,633,D4,245,BENNETT AVENUE,...,0,0,0,1951,2,D4,"585,000",05/16/2019,2,1
10440,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,633,D4,273,BENNETT AVENUE,...,0,0,0,1951,2,D4,"589,000",07/24/2019,2,1
10441,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,614,D4,720,FORT WASHINGTON AVENUE,...,0,0,0,1939,2,D4,"800,000",06/26/2019,2,1
10442,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,166,D4,736,WEST 186TH STREET,...,0,0,0,1939,2,D4,"850,000",07/08/2019,3,2
10443,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,614,D4,720,FORT WASHINGTON AVENUE,...,0,0,0,1939,2,D4,"895,000",06/21/2019,2,2
10444,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,628,D4,730,FORT WASHINGTON AVENUE,...,0,0,0,1939,2,D4,"899,000",08/06/2019,2,2
10445,2019,WASHINGTON HEIGHTS UPPER,10,COOPS - ELEVATOR APARTMENTS,2,2180,70,D4,24,BENNETT AVENUE,...,0,0,0,1920,2,D4,"1,050,000",07/02/2019,3,2
10446,2019,WASHINGTON HEIGHTS UPPER,13,CONDOS - ELEVATOR APARTMENTS,2,2164,1087,R4,160,WADSWORTH AVENUE,...,0,0,527,0,2,R4,"375,000",01/16/2019,1,1
10447,2019,WASHINGTON HEIGHTS UPPER,13,CONDOS - ELEVATOR APARTMENTS,2,2164,1019,R4,4260,BROADWAY,...,0,0,682,0,2,R4,"405,000",01/08/2019,2,2
10448,2019,WASHINGTON HEIGHTS UPPER,13,CONDOS - ELEVATOR APARTMENTS,2,2164,1062,R4,4260,BROADWAY,...,0,0,751,0,2,R4,"530,000",08/26/2019,3,1
10449,2019,WASHINGTON HEIGHTS UPPER,13,CONDOS - ELEVATOR APARTMENTS,2,2164,1118,R4,160,WADSWORTH AVENUE,...,0,0,"1,018",0,2,R4,"630,000",06/14/2019,4,1
10450,2019,WASHINGTON HEIGHTS UPPER,13,CONDOS - ELEVATOR APARTMENTS,2,2164,1063,R4,4260,BROADWAY,...,0,0,682,0,2,R4,"650,000",08/14/2019,2,1
10451,2019,WASHINGTON HEIGHTS UPPER,13,CONDOS - ELEVATOR APARTMENTS,2,2180,1428,R4,69,BENNETT AVENUE,...,0,0,565,1954,2,R4,"412,500",09/09/2019,1,1
10452,2019,WASHINGTON HEIGHTS UPPER,13,CONDOS - ELEVATOR APARTMENTS,2,2180,1541,R4,105,BENNETT AVENUE,...,0,0,"1,109",1939,2,R4,"740,000",02/26/2019,2,2

In [4]:
matched.to_csv('~/Desktop/workspace/FinalProject/matched_data_cleanup.csv', index=False)

In [7]:
matched.groupby(["ZipCode"])["Beds"].count().reset_index()

    ZipCode  Beds
0     10001   105
1     10002   263
2     10003   404
3     10004     8
4     10005    38
5     10006    21
6     10007    86
7     10009   143
8     10010   160
9     10011   641
10    10012   316
11    10013   171
12    10014   426
13    10016   561
14    10017     1
15    10018    15
16    10019   468
17    10021   607
18    10022   453
19    10023  1079
20    10024   791
21    10025   647
22    10026    40
23    10027   101
24    10028   509
25    10029    41
26    10030    19
27    10031    13
28    10032    51
29    10033   120
30    10034    61
31    10035    43
32    10036   302
33    10037     8
34    10038    97
35    10039     9
36    10040    84
37    10065   360
38    10069     2
39    10075   502
40    10128   686
41    10280     1