In [77]:
import pandas as pd

# Reading the original csv file
data = pd.read_csv("merged_manhattan.csv", header = 0)

In [78]:
# Clean up the column names
def colnames(original):
    newcols = []
    for col in original:
        newcol = col.title().replace("\n", "").replace(" ", "")
        newcols.append(newcol)
    return newcols

data.columns = colnames(data.columns)
display(data.head())

,Year,Neighborhood,BuildingClassCategory,TaxClassAtPresent,Block,Lot,BuildingClassAtPresent,Address,ApartmentNumber,ZipCode,ResidentialUnits,CommercialUnits,TotalUnits,LandSquareFeet,GrossSquareFeet,YearBuilt,TaxClassAtTimeOfSale,BuildingClassAtTimeOfSale,SalePrice,SaleDate
0,2015,ALPHABET CITY,01 ONE FAMILY DWELLINGS,1,400,19,A4,526 EAST 5TH STREET,,10009,1,0,1,1883,5200,1900,1,A4,6500000,3/18/2015
1,2015,ALPHABET CITY,03 THREE FAMILY DWELLINGS,1,376,24,C0,264 EAST 7TH STREET,,10009,3,0,3,2059,3696,1900,1,C0,3775000,10/22/2015
2,2015,ALPHABET CITY,03 THREE FAMILY DWELLINGS,1,377,66,C0,243 EAST 7TH STREET,,10009,3,0,3,2381,3084,1899,1,C0,2900000,6/24/2015
3,2015,ALPHABET CITY,04 TAX CLASS 1 CONDOS,1C,399,1101,R6,238 EAST 4TH STREET,-,10009,1,0,1,0,0,1955,1,R6,6995000,6/15/2015
4,2015,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,376,7,C4,102 AVENUE C,,10009,26,3,29,3772,16679,1900,2,C4,14550000,2/5/2015

In [79]:
# Building class category number and description as separated variables

category_num = [x[:2] for x in data.BuildingClassCategory]
category_des = [x[3:] for x in data.BuildingClassCategory]

data['BuildingCategoryNum'] = category_num
data['BuildingCategoryDes'] = category_des
data = data.drop(columns = ['BuildingClassCategory'])

display(data.head())

,Year,Neighborhood,TaxClassAtPresent,Block,Lot,BuildingClassAtPresent,Address,ApartmentNumber,ZipCode,ResidentialUnits,...,TotalUnits,LandSquareFeet,GrossSquareFeet,YearBuilt,TaxClassAtTimeOfSale,BuildingClassAtTimeOfSale,SalePrice,SaleDate,BuildingCategoryNum,BuildingCategoryDes
0,2015,ALPHABET CITY,1,400,19,A4,526 EAST 5TH STREET,,10009,1,...,1,1883,5200,1900,1,A4,6500000,3/18/2015,01,ONE FAMILY DWELLINGS
1,2015,ALPHABET CITY,1,376,24,C0,264 EAST 7TH STREET,,10009,3,...,3,2059,3696,1900,1,C0,3775000,10/22/2015,03,THREE FAMILY DWELLINGS
2,2015,ALPHABET CITY,1,377,66,C0,243 EAST 7TH STREET,,10009,3,...,3,2381,3084,1899,1,C0,2900000,6/24/2015,03,THREE FAMILY DWELLINGS
3,2015,ALPHABET CITY,1C,399,1101,R6,238 EAST 4TH STREET,-,10009,1,...,1,0,0,1955,1,R6,6995000,6/15/2015,04,TAX CLASS 1 CONDOS
4,2015,ALPHABET CITY,2,376,7,C4,102 AVENUE C,,10009,26,...,29,3772,16679,1900,2,C4,14550000,2/5/2015,07,RENTALS - WALKUP APARTMENTS

In [80]:
# Split the address into StreetNum / StreetName / AptNum

streetnum = [x.split(maxsplit = 1)[0] for x in data.Address]
streetname = [x.split(maxsplit = 1)[-1] for x in data.Address]

aptnum = []
for add in streetname:
    if "," in add:
        splitadd = add.split(",", maxsplit = 1)[-1]
        aptnum.append(splitadd)
    else:
        aptnum.append("")

streetname_fin = []
for idx, stname in enumerate(streetname):
    if aptnum[idx] == stname[-len(aptnum[idx]):]:
        stname = stname[:-len(aptnum[idx])].replace(",", "")
        streetname_fin.append(stname)
    else:
        stname = stname
        streetname_fin.append(stname)
        
data['StreetNum'] = streetnum
data['StreetName'] = streetname_fin
data['AptNum'] = aptnum        
data = data.drop(columns = ['Address', 'ApartmentNumber'])

display(data.head())

,Year,Neighborhood,TaxClassAtPresent,Block,Lot,BuildingClassAtPresent,ZipCode,ResidentialUnits,CommercialUnits,TotalUnits,...,YearBuilt,TaxClassAtTimeOfSale,BuildingClassAtTimeOfSale,SalePrice,SaleDate,BuildingCategoryNum,BuildingCategoryDes,StreetNum,StreetName,AptNum
0,2015,ALPHABET CITY,1,400,19,A4,10009,1,0,1,...,1900,1,A4,6500000,3/18/2015,01,ONE FAMILY DWELLINGS,526,EAST 5TH STREET,
1,2015,ALPHABET CITY,1,376,24,C0,10009,3,0,3,...,1900,1,C0,3775000,10/22/2015,03,THREE FAMILY DWELLINGS,264,EAST 7TH STREET,
2,2015,ALPHABET CITY,1,377,66,C0,10009,3,0,3,...,1899,1,C0,2900000,6/24/2015,03,THREE FAMILY DWELLINGS,243,EAST 7TH STREET,
3,2015,ALPHABET CITY,1C,399,1101,R6,10009,1,0,1,...,1955,1,R6,6995000,6/15/2015,04,TAX CLASS 1 CONDOS,238,EAST 4TH STREET,
4,2015,ALPHABET CITY,2,376,7,C4,10009,26,3,29,...,1900,2,C4,14550000,2/5/2015,07,RENTALS - WALKUP APARTMENTS,102,AVENUE C,

In [81]:
# Rearranging columns

data = data[['Year', 'Neighborhood', 'BuildingCategoryNum', 'BuildingCategoryDes', 
            'TaxClassAtPresent', 'Block', 'Lot', 'BuildingClassAtPresent', 
            'StreetNum', 'StreetName', 'AptNum', 'ZipCode', 'ResidentialUnits',
            'CommercialUnits', 'TotalUnits', 'LandSquareFeet', 'GrossSquareFeet',
            'YearBuilt', 'TaxClassAtTimeOfSale', 'BuildingClassAtTimeOfSale',
            'SalePrice', 'SaleDate']]

display(data.head())
data.shape

,Year,Neighborhood,BuildingCategoryNum,BuildingCategoryDes,TaxClassAtPresent,Block,Lot,BuildingClassAtPresent,StreetNum,StreetName,...,ResidentialUnits,CommercialUnits,TotalUnits,LandSquareFeet,GrossSquareFeet,YearBuilt,TaxClassAtTimeOfSale,BuildingClassAtTimeOfSale,SalePrice,SaleDate
0,2015,ALPHABET CITY,01,ONE FAMILY DWELLINGS,1,400,19,A4,526,EAST 5TH STREET,...,1,0,1,1883,5200,1900,1,A4,6500000,3/18/2015
1,2015,ALPHABET CITY,03,THREE FAMILY DWELLINGS,1,376,24,C0,264,EAST 7TH STREET,...,3,0,3,2059,3696,1900,1,C0,3775000,10/22/2015
2,2015,ALPHABET CITY,03,THREE FAMILY DWELLINGS,1,377,66,C0,243,EAST 7TH STREET,...,3,0,3,2381,3084,1899,1,C0,2900000,6/24/2015
3,2015,ALPHABET CITY,04,TAX CLASS 1 CONDOS,1C,399,1101,R6,238,EAST 4TH STREET,...,1,0,1,0,0,1955,1,R6,6995000,6/15/2015
4,2015,ALPHABET CITY,07,RENTALS - WALKUP APARTMENTS,2,376,7,C4,102,AVENUE C,...,26,3,29,3772,16679,1900,2,C4,14550000,2/5/2015

(69502, 22)

In [82]:
# Deleting instances whose sale prices are lower than $200,000

intprice = []
for price in data.SalePrice:
    if type(price) == str:
        nocomma = price.replace(",", "")
        newprice = int(nocomma)
        intprice.append(newprice)
    else:
        intprice.append(price)

boolean = [x < 200000 for x in intprice]
data.drop(data[boolean].index, inplace=True)

data.shape

(68067, 22)

In [83]:
# Dropping duplicated rows

duplicates = data[data.duplicated(keep=False)]
print("Printing duplicated rows:")
display(duplicates)

data.drop_duplicates(keep='first', inplace=True)

data.shape

Printing duplicated rows:

,Year,Neighborhood,BuildingCategoryNum,BuildingCategoryDes,TaxClassAtPresent,Block,Lot,BuildingClassAtPresent,StreetNum,StreetName,...,ResidentialUnits,CommercialUnits,TotalUnits,LandSquareFeet,GrossSquareFeet,YearBuilt,TaxClassAtTimeOfSale,BuildingClassAtTimeOfSale,SalePrice,SaleDate
734,2015,CHELSEA,15,CONDOS - 2-10 UNIT RESIDENTIAL,2C,769,1508,R1,234,WEST 20TH STREET,...,1,0,1,0,0,1929,2,R1,2090000,7/7/2015
735,2015,CHELSEA,15,CONDOS - 2-10 UNIT RESIDENTIAL,2C,769,1508,R1,234,WEST 20TH STREET,...,1,0,1,0,0,1929,2,R1,2090000,7/7/2015
4397,2015,HARLEM-CENTRAL,14,RENTALS - 4-10 UNIT,2A,1921,25,S4,111,WEST 136,...,4,1,5,1665,2789,1910,2,S4,900000,8/21/2015
4398,2015,HARLEM-CENTRAL,14,RENTALS - 4-10 UNIT,2A,1921,25,S4,111,WEST 136,...,4,1,5,1665,2789,1910,2,S4,900000,8/21/2015
4417,2015,HARLEM-CENTRAL,15,CONDOS - 2-10 UNIT RESIDENTIAL,2C,1904,1103,R1,103,WEST 119TH STREET,...,1,0,1,0,0,0,2,R1,830000,9/28/2015
4418,2015,HARLEM-CENTRAL,15,CONDOS - 2-10 UNIT RESIDENTIAL,2C,1904,1103,R1,103,WEST 119TH STREET,...,1,0,1,0,0,0,2,R1,830000,9/28/2015
4631,2015,HARLEM-UPPER,03,THREE FAMILY DWELLINGS,1,2084,4,C0,3688,BROADWAY,...,3,0,3,1666,3776,1910,1,C0,800000,5/7/2015
4632,2015,HARLEM-UPPER,03,THREE FAMILY DWELLINGS,1,2084,4,C0,3688,BROADWAY,...,3,0,3,1666,3776,1910,1,C0,800000,5/7/2015
5618,2015,MANHATTAN VALLEY,13,CONDOS - ELEVATOR APARTMENTS,2,1833,1263,R4,382,CENTRAL PARK WEST,...,1,0,1,0,0,1961,2,R4,1810000,1/21/2015
5619,2015,MANHATTAN VALLEY,13,CONDOS - ELEVATOR APARTMENTS,2,1833,1263,R4,382,CENTRAL PARK WEST,...,1,0,1,0,0,1961,2,R4,1810000,1/21/2015
7432,2015,MIDTOWN WEST,13,CONDOS - ELEVATOR APARTMENTS,2,1032,1379,R4,350,WEST 42ND STREET,...,1,0,1,0,0,2004,2,R4,2115000,3/11/2015
7433,2015,MIDTOWN WEST,13,CONDOS - ELEVATOR APARTMENTS,2,1032,1379,R4,350,WEST 42ND STREET,...,1,0,1,0,0,2004,2,R4,2115000,3/11/2015
9037,2015,TRIBECA,13,CONDOS - ELEVATOR APARTMENTS,2,16,1629,R4,30,LITTLE WEST STREET,...,1,0,1,0,0,2005,2,R4,3190000,8/26/2015
9038,2015,TRIBECA,13,CONDOS - ELEVATOR APARTMENTS,2,16,1629,R4,30,LITTLE WEST STREET,...,1,0,1,0,0,2005,2,R4,3190000,8/26/2015
10827,2015,UPPER EAST SIDE (59-79),17,CONDO COOPS,2,1373,1901,R9,551,MAIN STREET,...,0,0,0,0,0,1975,2,R9,259512,8/4/2015
10828,2015,UPPER EAST SIDE (59-79),17,CONDO COOPS,2,1373,1901,R9,551,MAIN STREET,...,0,0,0,0,0,1975,2,R9,259512,8/4/2015
10918,2015,UPPER EAST SIDE (59-79),17,CONDO COOPS,2,1373,1901,R9,551,MAIN STREET,...,0,0,0,0,0,1975,2,R9,420902,8/26/2015
10919,2015,UPPER EAST SIDE (59-79),17,CONDO COOPS,2,1373,1901,R9,551,MAIN STREET,...,0,0,0,0,0,1975,2,R9,420902,8/26/2015
10975,2015,UPPER EAST SIDE (59-79),17,CONDO COOPS,2,1373,1901,R9,551,MAIN STREET,...,0,0,0,0,0,1975,2,R9,513379,9/16/2015
10976,2015,UPPER EAST SIDE (59-79),17,CONDO COOPS,2,1373,1901,R9,551,MAIN STREET,...,0,0,0,0,0,1975,2,R9,513379,9/16/2015
11566,2015,UPPER EAST SIDE (79-96),10,COOPS - ELEVATOR APARTMENTS,2,1509,51,D4,140,EAST 81ST STREET,...,0,0,0,0,0,1928,2,D4,3787500,6/24/2015
11567,2015,UPPER EAST SIDE (79-96),10,COOPS - ELEVATOR APARTMENTS,2,1509,51,D4,140,EAST 81ST STREET,...,0,0,0,0,0,1928,2,D4,3787500,6/24/2015
13497,2015,UPPER WEST SIDE (59-79),13,CONDOS - ELEVATOR APARTMENTS,2,1171,1818,R4,220,RIVERSIDE BOULEVARD,...,1,0,1,0,0,0,2,R4,745000,4/14/2015
13498,2015,UPPER WEST SIDE (59-79),13,CONDOS - ELEVATOR APARTMENTS,2,1171,1818,R4,220,RIVERSIDE BOULEVARD,...,1,0,1,0,0,0,2,R4,745000,4/14/2015
13501,2015,UPPER WEST SIDE (59-79),13,CONDOS - ELEVATOR APARTMENTS,2,1171,1016,R4,200,RIVERSIDE BOULEVARD,...,1,0,1,0,0,0,2,R4,890000,12/28/2015
13502,2015,UPPER WEST SIDE (59-79),13,CONDOS - ELEVATOR APARTMENTS,2,1171,1016,R4,200,RIVERSIDE BOULEVARD,...,1,0,1,0,0,0,2,R4,890000,12/28/2015
14531,2015,UPPER WEST SIDE (79-96),13,CONDOS - ELEVATOR APARTMENTS,2,1206,1069,R4,327,CENTRAL PARK WEST,...,1,0,1,0,0,0,2,R4,1961000,11/4/2015
14532,2015,UPPER WEST SIDE (79-96),13,CONDOS - ELEVATOR APARTMENTS,2,1206,1069,R4,327,CENTRAL PARK WEST,...,1,0,1,0,0,0,2,R4,1961000,11/4/2015
16371,2016,CHELSEA,13,CONDOS - ELEVATOR APARTMENTS,2,774,1042,R4,252,SEVENTH AVENUE,...,1,0,1,0,0,0,2,R4,1500000,10/5/2016
16372,2016,CHELSEA,13,CONDOS - ELEVATOR APARTMENTS,2,774,1042,R4,252,SEVENTH AVENUE,...,1,0,1,0,0,0,2,R4,1500000,10/5/2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68534,2019,UPPER WEST SIDE (79-96),10,COOPS - ELEVATOR APARTMENTS,2,1242,62,D4,710,WEST END AVENUE,...,0,0,0,0,0,1928,2,D4,"805,000",03/04/2019
68535,2019,UPPER WEST SIDE (79-96),10,COOPS - ELEVATOR APARTMENTS,2,1242,62,D4,710,WEST END AVENUE,...,0,0,0,0,0,1928,2,D4,"805,000",03/04/2019
68699,2019,UPPER WEST SIDE (79-96),13,CONDOS - ELEVATOR APARTMENTS,2,1213,1178,R4,127,WEST 82ND STREET,...,0,0,0,0,692,1912,2,R4,"999,000",07/26/2019
68700,2019,UPPER WEST SIDE (79-96),13,CONDOS - ELEVATOR APARTMENTS,2,1213,1178,R4,127,WEST 82ND STREET,...,0,0,0,0,692,1912,2,R4,"999,000",07/26/2019
68701,2019,UPPER WEST SIDE (79-96),13,CONDOS - ELEVATOR APARTMENTS,2,1213,1157,R4,127,WEST 82ND STREET,...,0,0,0,0,952,1912,2,R4,"1,275,000",08/14/2019
68702,2019,UPPER WEST SIDE (79-96),13,CONDOS - ELEVATOR APARTMENTS,2,1213,1157,R4,127,WEST 82ND STREET,...,0,0,0,0,952,1912,2,R4,"1,275,000",08/14/2019
68703,2019,UPPER WEST SIDE (79-96),13,CONDOS - ELEVATOR APARTMENTS,2,1213,1185,R4,127,WEST 82ND STREET,...,0,0,0,0,453,1912,2,R4,"1,955,000",01/02/2019
68704,2019,UPPER WEST SIDE (79-96),13,CONDOS - ELEVATOR APARTMENTS,2,1213,1185,R4,127,WEST 82ND STREET,...,0,0,0,0,453,1912,2,R4,"1,955,000",01/02/2019
68705,2019,UPPER WEST SIDE (79-96),13,CONDOS - ELEVATOR APARTMENTS,2,1213,1161,R4,127,WEST 82ND STREET,...,0,0,0,0,391,1912,2,R4,"1,955,000",01/02/2019
68706,2019,UPPER WEST SIDE (79-96),13,CONDOS - ELEVATOR APARTMENTS,2,1213,1161,R4,127,WEST 82ND STREET,...,0,0,0,0,391,1912,2,R4,"1,955,000",01/02/2019
68798,2019,UPPER WEST SIDE (79-96),13,CONDOS - ELEVATOR APARTMENTS,2,1232,1127,R4,500,WEST END AVENUE,...,0,0,0,0,852,0,2,R4,"814,000",03/12/2019
68799,2019,UPPER WEST SIDE (79-96),13,CONDOS - ELEVATOR APARTMENTS,2,1232,1127,R4,500,WEST END AVENUE,...,0,0,0,0,852,0,2,R4,"814,000",03/12/2019
68860,2019,UPPER WEST SIDE (79-96),13,CONDOS - ELEVATOR APARTMENTS,2,1253,1145,R4,222,RIVERSIDE DRIVE,...,0,0,0,0,"1,178",0,2,R4,"1,800,000",12/19/2018
68861,2019,UPPER WEST SIDE (79-96),13,CONDOS - ELEVATOR APARTMENTS,2,1253,1145,R4,222,RIVERSIDE DRIVE,...,0,0,0,0,"1,178",0,2,R4,"1,800,000",12/19/2018
68878,2019,UPPER WEST SIDE (79-96),17,CONDO COOPS,2,1213,1209,R9,109,WEST 82ND STREET,...,0,0,0,0,0,0,2,R9,"680,000",08/01/2019
68879,2019,UPPER WEST SIDE (79-96),17,CONDO COOPS,2,1213,1209,R9,109,WEST 82ND STREET,...,0,0,0,0,0,0,2,R9,"680,000",08/01/2019
68880,2019,UPPER WEST SIDE (79-96),17,CONDO COOPS,2,1213,1209,R9,111,WEST 82ND STREET,...,0,0,0,0,0,0,2,R9,"720,000",04/29/2019
68881,2019,UPPER WEST SIDE (79-96),17,CONDO COOPS,2,1213,1209,R9,111,WEST 82ND STREET,...,0,0,0,0,0,0,2,R9,"720,000",04/29/2019
68890,2019,UPPER WEST SIDE (79-96),17,CONDO COOPS,2,1232,1002,R9,255,WEST 84TH STREET,...,0,0,0,0,0,1915,2,R9,"228,000",08/22/2019
68891,2019,UPPER WEST SIDE (79-96),17,CONDO COOPS,2,1232,1002,R9,255,WEST 84TH STREET,...,0,0,0,0,0,1915,2,R9,"228,000",08/22/2019
68892,2019,UPPER WEST SIDE (79-96),17,CONDO COOPS,2,1232,1002,R9,255,WEST 84TH STREET,...,0,0,0,0,0,1915,2,R9,"560,000",10/22/2018
68893,2019,UPPER WEST SIDE (79-96),17,CONDO COOPS,2,1232,1002,R9,255,WEST 84TH STREET,...,0,0,0,0,0,1915,2,R9,"560,000",10/22/2018
68894,2019,UPPER WEST SIDE (79-96),17,CONDO COOPS,2,1232,1002,R9,255,WEST 84TH STREET,...,0,0,0,0,0,1915,2,R9,"1,270,000",09/09/2019
68895,2019,UPPER WEST SIDE (79-96),17,CONDO COOPS,2,1232,1002,R9,255,WEST 84TH STREET,...,0,0,0,0,0,1915,2,R9,"1,270,000",09/09/2019
68896,2019,UPPER WEST SIDE (79-96),17,CONDO COOPS,2,1232,1002,R9,255,WEST 84TH STREET,...,0,0,0,0,0,1915,2,R9,"1,950,000",02/11/2019
68897,2019,UPPER WEST SIDE (79-96),17,CONDO COOPS,2,1232,1002,R9,255,WEST 84TH STREET,...,0,0,0,0,0,1915,2,R9,"1,950,000",02/11/2019
69181,2019,WASHINGTON HEIGHTS LOWER,01,ONE FAMILY DWELLINGS,1,2118,67,A9,565,WEST 159TH STREET,...,1,0,1,"1,499","2,400",1910,1,A9,"950,000",07/11/2019
69182,2019,WASHINGTON HEIGHTS LOWER,01,ONE FAMILY DWELLINGS,1,2118,67,A9,565,WEST 159TH STREET,...,1,0,1,"1,499","2,400",1910,1,A9,"950,000",07/11/2019
69186,2019,WASHINGTON HEIGHTS LOWER,02,TWO FAMILY DWELLINGS,1,2118,61,B9,553,WEST 159 STREET,...,2,0,2,"1,499","2,400",1920,1,B9,"1,315,000",08/21/2019
69187,2019,WASHINGTON HEIGHTS LOWER,02,TWO FAMILY DWELLINGS,1,2118,61,B9,553,WEST 159 STREET,...,2,0,2,"1,499","2,400",1920,1,B9,"1,315,000",08/21/2019

(67349, 22)